import {
  GenerateApiKey,
  ExpiresIn,
  RefreshApiKey,
  GenerateDisposableToken,
  DisposableTokenScope,
} from '../../../index';
import {IAuthClient} from '../../../clients/IAuthClient';
import {PermissionScope} from '../../../auth/tokens/permission-scope';
import {DisposableTokenProps} from '../../../auth/tokens/disposable-token-scope';

export interface BaseAuthClientProps {
  createAuthClient: () => IAuthClient;
}
export abstract class AbstractAuthClient implements IAuthClient {
  // making these protected until we fully abstract away the nodejs client
  protected readonly authClient: IAuthClient;

  protected constructor(props: BaseAuthClientProps) {
    this.authClient = props.createAuthClient();
  }

  /**
   * Generates a new, scoped API key along with a refresh token to refresh it before expiry.
   *
   * **Important:** The API key returned by this method is in the legacy v1 format.
   * V1 are keys are now deprecated and support for them may be removed in a future release.
   *
   * @param {PermissionScope} scope - controls the permissions that the new key will have
   * @param {ExpiresIn} expiresIn - how long the API key should be valid for
   * @returns {Promise<GenerateApiKey.Response>} -
   * {@link GenerateApiKey.Success} containing the API key, refresh token, endpoint and epoch timestamp when the key expires.
   * If the key never expires, no refresh token will be returned and the expiry timestamp will be infinite.
   * {@link GenerateApiKey.Error} on failure.
   */
  public async generateApiKey(
    scope: PermissionScope,
    expiresIn: ExpiresIn
  ): Promise<GenerateApiKey.Response> {
    return await this.authClient.generateApiKey(scope, expiresIn);
  }

  /**
   * @deprecated please use `generateApiKey` instead
   */
  public async generateAuthToken(
    scope: PermissionScope,
    expiresIn: ExpiresIn
  ): Promise<GenerateApiKey.Response> {
    return await this.generateApiKey(scope, expiresIn);
  }

  /**
   * Refreshes an API key generated by `generateApiKey`. Returns a new API key and refresh token.
   * The new key will be valid for the same duration as the original, starting from the time of refresh.
   * The original key remains valid until it expires.
   *
   * **Note:** Only API keys produced by `generateApiKey` (legacy v1 api keys) can be refreshed.
   * Disposable tokens generated by `generateDisposableToken` cannot be refreshed — generate a new one
   * when the old one expires.
   *
   * @param {string} refreshToken - the refresh token from a previous `generateApiKey` or `refreshApiKey` response
   * @returns {Promise<RefreshApiKey.Response>} -
   * {@link RefreshApiKey.Success} containing the new API key, refresh token, endpoint and epoch timestamp when the key expires.
   * {@link RefreshApiKey.Error} on failure.
   */
  public async refreshApiKey(
    refreshToken: string
  ): Promise<RefreshApiKey.Response> {
    return await this.authClient.refreshApiKey(refreshToken);
  }

  /**
   * @deprecated please use `refreshApiKey` instead
   */
  public async refreshAuthToken(
    refreshToken: string
  ): Promise<RefreshApiKey.Response> {
    return await this.refreshApiKey(refreshToken);
  }

  /**
   * Generates a new disposable token with fine-grained access control.
   * Disposable tokens are short-lived and cannot be refreshed.
   *
   * @param {DisposableTokenScope} scope - controls the permissions that the new token will have
   * @param {ExpiresIn} expiresIn - how long the token is valid for
   * @param {DisposableTokenProps} disposableTokenProps - additional properties, e.g. a tokenId for audit logging
   * @returns {Promise<GenerateDisposableToken.Response>} -
   * {@link GenerateDisposableToken.Success} containing the disposable token, endpoint and epoch timestamp when it expires.
   * {@link GenerateDisposableToken.Error} on failure.
   */
  public async generateDisposableToken(
    scope: DisposableTokenScope,
    expiresIn: ExpiresIn,
    disposableTokenProps?: DisposableTokenProps
  ): Promise<GenerateDisposableToken.Response> {
    return await this.authClient.generateDisposableToken(
      scope,
      expiresIn,
      disposableTokenProps
    );
  }
}
