name: Manual Release

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.release }}
    steps:
      - uses: actions/checkout@v2
      - name: Set release
        id: semrel
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-initial-development-versions: true
          force-bump-patch-version: true

      - name: Output release
        id: release
        run: echo "::set-output name=release::${{ steps.semrel.outputs.version }}"
  publish_javascript:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: release
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Configure Artifactory credentials
        run: |
          # lel this is how jfrog wants you to come up with your scoped npm configuration
          echo @momento:registry=https://momento.jfrog.io/artifactory/api/npm/npm-public/ >> ~/.npmrc

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Create .npmrc with npm auth github-token
        run: echo //registry.npmjs.org/:_authToken=$NPM_TOKEN > ~/.npmrc

      - name: Publish npm package
        run: |
          export VERSION="${{ needs.release.outputs.version }}"
          echo "Publishing package with version $VERSION"
          mv package.json package.json.ORIG
          cat package.json.ORIG|jq ". += {\"version\": \"$VERSION\"}" > package.json
          npm publish
        shell: bash
