name: Retry Tests

on:
  pull_request:
    branches: [main]

jobs:
  test-momento-local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Start Momento Local
        run: |
          docker run -d -p 8080:8080 gomomento/momento-local

      - name: Set script permissions
        run: chmod +x ./scripts/build-and-test-package-retry-tests.sh

      - name: Build and test with Momento Local
        env:
          MOMENTO_PORT: 8080
        run: |
          node -v
          ./scripts/build-and-test-package-retry-tests.sh

      - name: Clean up Docker Container
        run: docker rm -f momento-local || true
