# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Manual Web Sdk Snapshot Publish

on:
  workflow_dispatch:
    inputs:
      snapshhot-version:
        required: true
        description: Version will be published as `0.0.1-SNAPSHOT.${snapshot-version}`

jobs:
  publish_javascript_web:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Build web sdk
        run: |
          node -v
          ./scripts/build-package.sh "client-sdk-web"

      - name: Publish nodejs sdk package to npm
        run: |
          pushd ./packages/client-sdk-web
            npm publish --tag 0.0.1-SNAPSHOT.${{ github.event.inputs.snapshot-version }}
          popd
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
